mongo-addr: localhost:27017
api-addr: localhost:8082
state-server-admin: admin
# For locally running services.
identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
identity-location: http://localhost:8081/
# An agent is required for communicating with identity.
# agent-username: jem-0@admin@idm
# agent-key: {private: VnTcdjEOBBBjHNJ9knRtMA0I1PCATNySJXhW4PGE5hY=, public: MusIzFaXa7ImSMcQ9wgGpaDrgRQhbtsjsyawTvmXh1c=}
# For production identity manager (jemd will collect the correct public key on startup).
#identity-location: https://api.jujucharms.com/identity
