mongo-addr: localhost:27017
api-addr: localhost:8082
state-server-admin: admin
# For locally running services.
identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
identity-location: http://localhost:8081/
autocert: true
# An agent is required for communicating with identity.
# agent-username: jem-0@admin@idm
# agent-key: {private: VnTcdjEOBBBjHNJ9knRtMA0I1PCATNySJXhW4PGE5hY=, public: MusIzFaXa7ImSMcQ9wgGpaDrgRQhbtsjsyawTvmXh1c=}
# For production identity manager (jemd will collect the correct public key on startup).
#identity-location: https://api.jujucharms.com/identity
access-log: /var/log/jem/access.log
# The following certificate may be used for testing purposes. The second
# certificate in the chain is a root certificate. This can be used
# a ca-cert parameter in juju configuration and also installed in
# /usr/local/share/ca-certificates/jem.cnf for use with jaas-model.
# The certificate identifies itself as:
#  juju-apiserver
#  localhost
#  127.0.0.1
#  ::1
tls-cert: |
  -----BEGIN CERTIFICATE-----
  MIIBbDCCARYCCQCSJb9RIECG3TANBgkqhkiG9w0BAQsFADA9MQswCQYDVQQGEwJT
  STETMBEGA1UECAwKU29tZS1TdGF0ZTENMAsGA1UECgwEanVqdTEKMAgGA1UEAwwB
  KjAeFw0xNjA4MDcxOTIxMTJaFw0xNzA4MDcxOTIxMTJaMD0xCzAJBgNVBAYTAlNJ
  MRMwEQYDVQQIDApTb21lLVN0YXRlMQ0wCwYDVQQKDARqdWp1MQowCAYDVQQDDAEq
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj
  1+82fWZYwfP81zv8u5AAsfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAATAN
  BgkqhkiG9w0BAQsFAANBALT0/5yGpaGP9RaD+xRdoxGFf9m7g2IXUphlyN+KD4ST
  kjzzw0795c5I6Mt2HSbi7P+hP+9MGWi0jWpoO2Xj8M4=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIBbDCCARYCCQCSJb9RIECG3TANBgkqhkiG9w0BAQsFADA9MQswCQYDVQQGEwJT
  STETMBEGA1UECAwKU29tZS1TdGF0ZTENMAsGA1UECgwEanVqdTEKMAgGA1UEAwwB
  KjAeFw0xNjA4MDcxOTIxMTJaFw0xNzA4MDcxOTIxMTJaMD0xCzAJBgNVBAYTAlNJ
  MRMwEQYDVQQIDApTb21lLVN0YXRlMQ0wCwYDVQQKDARqdWp1MQowCAYDVQQDDAEq
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj
  1+82fWZYwfP81zv8u5AAsfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAATAN
  BgkqhkiG9w0BAQsFAANBALT0/5yGpaGP9RaD+xRdoxGFf9m7g2IXUphlyN+KD4ST
  kjzzw0795c5I6Mt2HSbi7P+hP+9MGWi0jWpoO2Xj8M4=
  -----END CERTIFICATE-----
tls-key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIBOwIBAAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj1+82fWZYwfP81zv8u5AA
  sfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAAQJBAMIh8Y7bkXtDcuR+j0Ij
  D7z9E0W3bhjK4jpXrKH71/ggFtyAJ/guMIlIZVcHqnjMcfu4nPrJDavWK/6F+A5S
  DQECIQD4Nr921aDOvJf9wyZu9Vl2fj+4w3i7jrDLDIwNpXx9zQIhANAjy7K4wf15
  kY3CiD24vrd+++uJPdNIhAYjKkYNoIDxAiEAzqDc4LNUS+YJ7VEwxHvwvsi4iToI
  XrKZkF7glFen/B0CIA3RgpGQAJkSfB5cPu1SGZ9XF+SQTQF8+/7oUMMr3m8RAiA0
  X9RasyDocy/n3dUGVMqum9O1QwAoBwu+AzgRqOECVA==
  -----END RSA PRIVATE KEY-----
controller-uuid: 00000000-0000-0000-0000-000000000001
default-cloud: aws
gui-location: https://jujucharms.com
