# Copyright 2021 Canonical Ltd
# See LICENSE file for licensing details.

options:
  candid-agent-private-key:
    type: string
    description: |
      Private key of the agent user for accessing the candid API.
  candid-agent-public-key:
    type: string
    description: |
      Public key of the agent user for accessing the candid API.
  candid-agent-username:
    type: string
    description: |
      Name of the agent user for accessing the candid API.
  candid-url:
    type: string
    description: URL of candid server 
  controller-admins:
    type: string
    description: |
       Whitespace separated list of candid users (or groups) that are
       made controller admins by default.
  uuid:
    type: string
    description: The UUID advertised by the JIMM controller.
