name: jaas
version: git
summary: JAAS client
description: Client for controlling JAAS multi-cloud juju controllers.
grade: stable
base: core18
confinement: strict

plugs:
  dot-local-share-juju:
    interface: personal-files
    read:
    - $HOME/.local/share/juju

apps:
  jimmctl:
    command: bin/wrappers/jimmctl
    plugs:
     - dot-local-share-juju
     - network

parts:
  jimmctl:
    plugin: gomod
    source: ../..
    source-type: git
    go-packages:
    - github.com/CanonicalLtd/jimm/cmd/jimmctl
    go-private:
    - github.com/CanonicalLtd
    prime:
     - bin/jimmctl
    override-build: |
      set -ex
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty`
      cp version/init.go.tmpl version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go
      snapcraftctl build

  files:
    plugin: dump
    source: files
    organize:
      jimmctl.wrapper: bin/wrappers/jimmctl
    prime:
      - bin/wrappers/jimmctl
