name: jimm
version: git
summary: Juju Intelligent Model Manager
description: Multi-cloud controller for managing JAAS models.
grade: stable
base: core20
confinement: strict

apps:
  jimm:
    command: bin/jimmsrv
    plugs:
     - network
     - network-bind

parts:
  jimmsrv:
    plugin: go
    source: ../..
    build-packages:
    - git
    - gcc
    override-pull: |-
      set -e
      snapcraftctl pull
      git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD | tee $SNAPCRAFT_PART_SRC/version/v/git-commit
      git -C $SNAPCRAFT_PART_SRC describe --dirty --abbrev=0 | tee $SNAPCRAFT_PART_SRC/version/v/version
      snapcraftctl set-version `cat $SNAPCRAFT_PART_SRC/version/v/version`
    override-build: |-
      set -e
      go install -mod readonly -p 16 -ldflags '-linkmode=external' github.com/CanonicalLtd/jimm/cmd/jimmsrv
